### ISSUE TITLE
Downloading the subtitles from iTunes fails

### ISSUE THREAD

**Issue by Essam311** [MichaelYochpaz/iSubRip#1]
Hi, when I try to download the subtitles from iTunes for the movie "Interstellar" using your script I get this message

https://itunes.apple.com/gb/movie/interstellar-2014/id965491522

![subs](https://user-images.githubusercontent.com/59211054/109546297-aa129f00-7ad2-11eb-9f2b-2b7f6794f269.png)

Does downloading the subtitles from iTunes using your script requires purchasing the movies?

**Comment by MichaelYochpaz** [comment]
@Essam311 No, it doesn't require purchasing the movie, and I just tested the link and it worked fine for me.
Did you install the required Python packages from [requirements.txt](https://github.com/MichaelYochpaz/iSubRip/blob/main/requirements.txt) and FFmpeg before running the script?

**Comment by Essam311** [comment]
@MichaelYochpaz I Installed the requirements and FFmpeg before running the script, but I'm not an expert in python, most likely i did something wrong or used the wrong files for FFmpeg,  any chance for compiling the script in an executable to run on windows so it be easier for using it for downloading the subtitles from iTunes for the novice users?

**Comment by jjehadtq** [comment]
> @Essam311 No, it doesn't require purchasing the movie.
> I just tested the same link and it worked fine for me.
> Did you install the required Python packages from [requirements.txt](https://github.com/MichaelYochpaz/iSubRip/blob/main/requirements.txt) and FFmpeg before running the script?

Same for me, and yes I downloaded the requirements and FFmpeg, I also tried many different movies and I still get "Download failed"

**Comment by Essam311** [comment]
@MichaelYochpaz Which FFmpeg version should I use from here?

https://github.com/BtbN/FFmpeg-Builds/releases

**Comment by Essam311** [comment]
@MichaelYochpaz I converted the script to exe but still getting "Download failed", could you test this exe on windows 64?

[iSubRip.zip](https://github.com/MichaelYochpaz/iSubRip/files/6074838/iSubRip.zip)

ffmpeg is not included in the exe (I tried merging them in the exe but the outcome file with the size of about 100 mega still needed ffmpeg to be in the path)

https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-03-01-12-33/ffmpeg-n4.3.2-160-gfbb9368226-win64-gpl-4.3.zip

(when i put ffmpeg.exe, ffplay.exe and ffprobe.exe in the same folder with the exe, the converted script did not ask for them)

**Comment by D-LUFFY89** [comment]
Hi, I have been trying out a iSubRip. The following message came out: What is done? 

https://i.imgur.com/ltsykgZ.jpg

All supplies have been installed 
pip3 install -r requirements.txt
+
FFmpeg


```
python3 iSubRip.py https://itunes.apple.com/gb/movie/interstellar-2014/id965491522
Scarping https://itunes.apple.com/gb/movie/interstellar-2014/id965491522
Found Movie: "Interstellar (2014)"
Traceback (most recent call last):
  File "iSubRip.py", line 155, in <module>
    main()
  File "iSubRip.py", line 51, in main
    if get_subtitles(url):
  File "iSubRip.py", line 83, in get_subtitles
    for item in page_script_dict["included"]:
KeyError: 'included'

```

**Comment by Essam311** [comment]
@MichaelYochpaz Is there likely to be missing python packages in `requirements.txt` like `lxml` for running the script on windows?

**Comment by MichaelYochpaz** [comment]
@Essam311 Seems like lxml was indeed missing from the requirements.txt (it's required for beautifulsoup to run), I've updated the requirements.txt file.

@jjehadtq @D-LUFFY89 Seems like either the site no longer has the subtitles stored on the webpage / they moved to a different location on the page, or iTunes started detecting and blocking page scraping.
I'll look into it once I have some free time and fix the script (if possible), but I'm pretty busy lately so it might take a while.

**Comment by Essam311** [comment]
@MichaelYochpaz Seems that the site still has the subtitles.

https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/playlist.m3u8?cc=GB&a=965491522&id=236366768&l=en&aec=SD

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_ap3",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="55653e6317a4e49b7bb9b7124feea77224bee9c044764a3f07c49f052face22b",URI="https://vod-ap3-amt.tv.apple.com/itunes-assets/HLSVideo124/v4/2d/07/c9/2d07c9c5-cd6b-0bdd-0071-3ef7955c3d86/P236366768_A965491522_FF_ar_subtitles.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_ak",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="55653e6317a4e49b7bb9b7124feea77224bee9c044764a3f07c49f052face22b",URI="https://vod-ak-amt.tv.apple.com/itunes-assets/HLSVideo124/v4/2d/07/c9/2d07c9c5-cd6b-0bdd-0071-3ef7955c3d86/P236366768_A965491522_FF_ar_subtitles.m3u8"

**Comment by MichaelYochpaz** [comment]
@Essam311 @jjehadtq @D-LUFFY89 I've updated the script, try running it now.

Note that the site has some issues in the past few weeks (sometimes loading iTunes pages returns an error), so it could cause the script to fail sometimes at random.
If the script fails try running it again after a few minutes and check if there's any difference.

**Comment by Essam311** [comment]
@MichaelYochpaz Thank you so much, downloading the subtitles from itunes.apple.com working great with version v1.0.2.

**Comment by Essam311** [comment]
@MichaelYochpaz Just a simple problem, in this Pre-Order movie "The Father" 2020 the script downloaded the subtitles of the movie "Blue Streak" 1999 instead of downloading the subtitles of the movie "The Father". The downloaded subtitles have the right file name "The.Father.iT.WEB" but don't have the right subtitles. 


https://itunes.apple.com/ae/movie/the-father/id1547866231

https://subscene.com/subtitles/the-father/english/2429906

https://itunes.apple.com/ae/movie/blue-streak/id531569899

https://subscene.com/subtitles/blue-streak/english/2362097
