### ISSUE TITLE
URLs without the movie title are not recognized

### ISSUE THREAD

**Issue by vevv** [MichaelYochpaz/iSubRip#13]
As in the title, example:
https://itunes.apple.com/us/movie/the-batman/id1606824145 works
https://itunes.apple.com/us/movie/id1606824145 doesn't

`Error: https://itunes.apple.com/us/movie/id1606824145 is not a valid iTunes movie URL.`

**Comment by MichaelYochpaz** [comment]
Thanks for letting me know.
I pushed a commit (64dad11399b82d2bb9c7d0a8dd587ab55d4df133) to fix that.

Might take some time until I push a new release though, so if it's causing you issues you can install the package from source:
https://github.com/MichaelYochpaz/iSubRip#git-source-code
