### ISSUE TITLE
Non-latin AppleTV URLs don't work

### ISSUE THREAD

**Issue by williameyelash** [MichaelYochpaz/iSubRip#15]
It says it's not a valid URL for Russian, Japanese and Chinese URLs.

**Comment by s-danilyak** [comment]
Sure thing!

https://tv.apple.com/hk/movie/%E6%B2%99%E4%B8%98%E7%80%9A%E6%88%B0/umc.cmc.2l7qj9p33t3jww1roxi8cgiw5?playableId=tvs.sbd.9001%3A1585877256

https://tv.apple.com/ru/movie/%D0%B4%D1%8E%D0%BD%D0%B0/umc.cmc.2l7qj9p33t3jww1roxi8cgiw5?playableId=tvs.sbd.9001%3A1585877256

https://tv.apple.com/jp/movie/dune%E3%83%86%E3%83%A5%E3%83%BC%E3%83%B3-%E7%A0%82%E3%81%AE%E6%83%91%E6%98%9F/umc.cmc.2l7qj9p33t3jww1roxi8cgiw5?playableId=tvs.sbd.9001%3A1585877256

**Comment by williameyelash** [comment]
https://tv.apple.com/eg/movie/%D9%86%D9%8A%D8%AA%D8%B1%D8%A7%D9%85/umc.cmc.5v5kcwojk2036614g73ob0tr9?playableId=tvs.sbd.9001%3A1612125024

**Comment by MichaelYochpaz** [comment]
Fixed in v2.3.1
