### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by erfanam7** [MichaelYochpaz/iSubRip#16]
![zzz](https://user-images.githubusercontent.com/76248115/176274449-a9bc39c2-2ebd-4da4-a147-6982f693cb20.jpg)
doesn't work anymore.
I cant download

**Comment by MichaelYochpaz** [comment]
Hey, this means there either aren't any subtitles for this movie, or that there are subtitles, but you've picked specific languages you want to download in the config and none of them were found.

Could you please post the URL as text, and your config (if you're using one)?

**Comment by williameyelash** [comment]
https://itunes.apple.com/us/movie/family-camp/id1623741785

Only Closed Captions are available for this one, so it's not isubrip's fault nothing gets downloaded. All good.

**Comment by erfanam7** [comment]
> Hey, this means there either aren't any subtitles for this movie, or that there are subtitles, but you've picked specific languages you want to download in the config and none of them were found.
> 
> Could you please post the URL as text, and your config (if you're using one)?

it does have subtitles but it can't download it. 
https://itunes.apple.com/us/movie/family-camp/id1623741785

**Comment by erfanam7** [comment]
> https://itunes.apple.com/us/movie/family-camp/id1623741785
> 
> Only Closed Captions are available for this one, so it's not isubrip's fault nothing gets downloaded. All good.

it does have cc English subtitles but can't download it

**Comment by williameyelash** [comment]
> > https://itunes.apple.com/us/movie/family-camp/id1623741785
> > Only Closed Captions are available for this one, so it's not isubrip's fault nothing gets downloaded. All good.
> 
> it does have cc English subtitles but can't download it

It never could.

**Comment by MichaelYochpaz** [comment]
As @williameyelash said, there are no subtitles available for this iTunes ID.

CC subtitles are not included in the manifest file, and as mentioned on #12 , it seems like they're embedded within the video stream (and extracting the subtitles from there is out of the scope of this project).

This has nothing to do with the latest release (it wouldn't work on any previous version).
