### ISSUE TITLE
[Feature request] Add AppleTV+ URL scraping

### ISSUE THREAD

**Issue by williameyelash** [MichaelYochpaz/iSubRip#17]
Seems like there's AppleTV and there's AppleTV+ that looks similar but isubrip doesn't work with the latter, and I couldn't get a working iTunes URL from the page source either. Please see the example below:

https://tv.apple.com/ca/movie/cha-cha-real-smooth/umc.cmc.6loo9fah7vwj2zpp7ehactlpd

Maybe it's not related to iTunes in any way and therefore not doable, no idea.

**Comment by vevv** [comment]
There's an iTunes link in the page source which can be extracted.
```py
def get_itunes_url(appletv_url):
    req = requests.get(url=appletv_url)
    search = re.search('itmss://(itunes.apple.com[^"]+)"', req.text)
    if search:
        return 'https://' + search[1].strip('\\')
```
