### ISSUE TITLE
Does not work on series

### ISSUE THREAD

**Issue by D-LUFFY89** [MichaelYochpaz/iSubRip#20]
Hi . Can it be made to work on series?
Example
https://tv.apple.com/us/show/anastasia-the-mystery-of-anna/umc.cmc.5uu89jcked7763y2qmfgdzjkx

Or how to get a link m3u8 ?

**Comment by MichaelYochpaz** [comment]
It has been discussed before on https://github.com/MichaelYochpaz/iSubRip/issues/12.

As I mentioned there, this would require some time-consuming code-rewrite, and I've yet to find a TV show that has additional subtitles other than CC.

The show you linked also has only "English (CC)" subtitles, which means there aren't any downloadable subtitles.

I prefer to invest the time I invest on this project in fixing / improving / implementing more useful features.
This is currently at a low priority and probably won't be implemented any time soon.

If you have any further questions / suggestions regarding this topic please use the existing issue I linked above.
