### ISSUE TITLE
[Bug] Errno 22 Invalid argument for some AppleTV URLs

### ISSUE THREAD

**Issue by williameyelash** [MichaelYochpaz/iSubRip#21]
Started to see this error for some AppleTV URLs. Examples:

https://tv.apple.com/it/movie/tarda-primavera/umc.cmc.3in0td23x10xki12falbfgkp3?playableId=tvs.sbd.9001%3A1061375559

https://tv.apple.com/gb/movie/adventures-of-don-juan/umc.cmc.6ub2tfb60nqbbx61vbrnlw3fg?playableId=tvs.sbd.9001%3A302343051

**Comment by MichaelYochpaz** [comment]
Fixed in the latest release (2.3.2)
