### ISSUE TITLE
Always redirected to the same subtitle pack.

### ISSUE THREAD

**Issue by rdamascena** [MichaelYochpaz/iSubRip#24]
Before this latest update (2.3.1), I was able to download different subtitle packs depending on which website language (iTunes or AppleTV) I selected. Now, apparently, regardless of the selected website language ("https://tv.apple.com/us/" or "https://tv.apple.com/br/"), the destination is always the same URL and hence the same subtitle pack. I want to download packages that contain Brazilian Portuguese subtitles and I am always redirected to the same URL and to the same subtitles package.

**Comment by MichaelYochpaz** [comment]
Could you please add an example and an explanation of what the issue with it is?  

I'm not sure what redirection you're talking about it.

**Comment by rdamascena** [comment]
**Before upgrading, version 2.3.0:**

> # isubrip "https://tv.apple.com/dm/movie/alita-battle-angel/umc.cmc.4fv2z93bd1rq9j2r1t5os93vf"
Note: You are currently using version 2.3.0 of isubrip, however version 2.3.1 is available.
Consider upgrading by running "python3 -m pip install --upgrade isubrip"

Scraping https://tv.apple.com/dm/movie/alita-battle-angel/umc.cmc.4fv2z93bd1rq9j2r1t5os93vf...
Found movie: Alita: Battle Angel
Downloading "العربية" (ar) subtitles...
Downloading "български" (bg) subtitles...
Downloading "中文（简体）" (cmn-Hans) subtitles...
Downloading "中文（繁體）" (cmn-Hant) subtitles...
Downloading "Čeština" (cs) subtitles...
Downloading "dansk" (da) subtitles...
Downloading "Deutsch (Deutschland)" (de-DE) subtitles...
Downloading "Ελληνικά" (el) subtitles...
Downloading "English (US)" (en-US) subtitles...
Downloading "Español (España)" (es-ES) subtitles...
Downloading "eesti" (et) subtitles...
Downloading "Suomi" (fi) subtitles...
Downloading "Français (France)" (fr-FR) subtitles...
Downloading "עברית" (he) subtitles...
Downloading "Hrvatski" (hr) subtitles...
Downloading "magyar" (hu) subtitles...
Downloading "Bahasa Indonesia" (id) subtitles...
Downloading "íslenska" (is) subtitles...
Downloading "Italiano (Italia)" (it-IT) subtitles...
Downloading "日本語" (ja) subtitles...
Downloading "한국어" (ko) subtitles...
Downloading "lietuvių" (lt) subtitles...
Downloading "latviešu" (lv) subtitles...
Downloading "Bahasa Melayu" (ms) subtitles...
Downloading "Nederlands" (nl) subtitles...
Downloading "norsk" (no) subtitles...
Downloading "polski" (pl) subtitles...
Downloading "Português (Brasil)" (pt-BR) subtitles...
Downloading "português (Portugal)" (pt-PT) subtitles...
Downloading "română" (ro) subtitles...
Downloading "Русский" (ru) subtitles...
Downloading "Slovenčina" (sk) subtitles...
Downloading "slovenščina" (sl) subtitles...
Downloading "srpski (latinica)" (sr-Latn) subtitles...
Downloading "Svenska" (sv) subtitles...
Downloading "ไทย" (th) subtitles...
Downloading "Türkçe" (tr) subtitles...
Downloading "українська" (uk) subtitles...
Downloading "Tiếng Việt" (vi) subtitles...
Downloading "廣東話" (yue-Hant) subtitles...
Downloading "English (US) " (en-US) subtitles...

Creating zip archive...

41/41 matching subtitles for "Alita: Battle Angel" were downloaded from 1 playlists to D:\subtitles".

**After updating, version 2.3.1:**

> # isubrip "https://tv.apple.com/dm/movie/alita-battle-angel/umc.cmc.4fv2z93bd1rq9j2r1t5os93vf"
Scraping https://tv.apple.com/dm/movie/alita-battle-angel/umc.cmc.4fv2z93bd1rq9j2r1t5os93vf...
Found movie: Alita: Battle Angel
Downloading "English (US)" (en-US) subtitles...
Downloading "English (US) " (en-US) subtitles...

Creating zip archive...

2/2 matching subtitles for "Alita: Battle Angel" were downloaded from 1 playlists to D:\subtitles".

**Comment by MichaelYochpaz** [comment]
Fixed in the latest release (2.3.2)
