### ISSUE TITLE
[bug] Some AppleTV URLs aren't working

### ISSUE THREAD

**Issue by williameyelash** [MichaelYochpaz/iSubRip#25]
Have encountered a problem with some AppleTV URLs. Examples:

https://tv.apple.com/cz/movie/zodiac/umc.cmc.72ndda4xnbbkiggs8mk8ndpfk?playableId=tvs.sbd.9001%3A527042918

https://tv.apple.com/ca/movie/official-competition/umc.cmc.yvbofv5kv6myeu4icgjq6ne5?playableId=tvs.sbd.9001%3A1633521224

**Comment by MichaelYochpaz** [comment]
Same issue as https://github.com/MichaelYochpaz/iSubRip/issues/24, currently working on a fix.
