### ISSUE TITLE
Hebrew SubRip Error

### ISSUE THREAD

**Issue by MyGitHub5** [MichaelYochpaz/iSubRip#26]
https://itunes.apple.com/il/movie/top-gun-maverick/id1622175422

https://itunes.apple.com/il/movie/monster-trucks/id1181629316

**Comment by MichaelYochpaz** [comment]
First one is a pre-order (not available yet), second one works fine for me.
You'll have to put more effort when asking for help, I can't guess what the issue is if you just paste links without any context.

**Comment by MyGitHub5** [comment]
The second not work for me..
Config: He with RTL
Same Config work with another movies

Scraping https://itunes.apple.com/il/movie/monster-trucks/id1181629316...
Found movie: Monster Trucks

0/0 matching subtitles for "Monster Trucks" were downloaded from 1 playlists to /tmp".

**Comment by MichaelYochpaz** [comment]
Please post the config you're using

**Comment by MyGitHub5** [comment]
`# This is the default config.
# This file should NOT be altered. For changing settings, use a user-config file.
# Any settings set on the user config will override these.

[general]
check-for-updates = false

[downloads]
folder = "/tmp/"
format = "srt"
languages = ["he"]
merge-playlists = false
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
zip = false

[scraping]
user-agent = "iTunes-AppleTV/15.2"

[subtitles]
fix-rtl = true
rtl-languages = ["ar", "he"]
remove-duplicates = true`

**Comment by MichaelYochpaz** [comment]
The language code for Hebrew in this case (for https://itunes.apple.com/il/movie/monster-trucks/id1181629316)  is `he-IL`, so you'll have to add it to your list of languages to download.
```toml
languages = ["he", "he-IL"]
```

You can always check your self by removing the `languages` setting from your config, which will result in downloading all of the available subtitles, where you can see the language code for each downloaded subtitles file.

Also, a small tip:
Don't put settings where you use the default values in your config.
It will help avoid issues in the future for changing one of them by mistake.
You can just use the following config, which will have the same effect:
```toml
[general]
check-for-updates = false

[downloads]
folder = "/tmp/"
format = "srt"
languages = ["he", "he-IL"]

[subtitles]
fix-rtl = true
```
