### ISSUE TITLE
[Issue]: URLs without the title name (tv.apple.com) aren't recognized

### ISSUE THREAD

**Issue by vevv** [MichaelYochpaz/iSubRip#29]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing open issue for the issue I want to report.

### OS Type

Linux

### Python Version

3.8.9

### Package Version

2.3.2

### Description

Links without the movie name on tv.apple.com don't work, similar to https://github.com/MichaelYochpaz/iSubRip/issues/13.

https://tv.apple.com/us/movie/umc.cmc.5cxq4yswbsp3apykshwrcb890 doesn't work
https://tv.apple.com/us/movie/a/umc.cmc.5cxq4yswbsp3apykshwrcb890w works (despite not being a valid URL, as only the ID matters)
https://tv.apple.com/us/movie/everything-everywhere-all-at-once/umc.cmc.5cxq4yswbsp3apykshwrcb890 also works

### Output Log

```Text
Error: https://tv.apple.com/us/movie/umc.cmc.5cxq4yswbsp3apykshwrcb890 is not a valid iTunes/AppleTV movie URL.
```

**Comment by MichaelYochpaz** [comment]
Thanks for reporting.
I pushed a fix on 3120b7cdc58a946b9448f3712ed2c4ce663acb94, the fix will be included in the next release.
