### ISSUE TITLE
The subtitle is overwritten by closed captions

### ISSUE THREAD

**Issue by Essam311** [MichaelYochpaz/iSubRip#3]
Hi, when I try to download the subtitles from this link for the movie "Star Wars: The Rise of Skywalker" the English subtitle is overwritten by the closed captions, an identification might need to be added to the closed captions files, something like ".cc".

https://itunes.apple.com/gb/movie/star-wars-the-rise-of-skywalker/id1490366967

![2222](https://user-images.githubusercontent.com/59211054/115159090-bad2a080-a091-11eb-8a20-8e3bf772013d.png)

https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/playlist.m3u8?cc=GB&a=1490366967&id=186755466&l=en&aec=SD

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_ap",LANGUAGE="en",NAME="English ",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound",FORCED=NO,STABLE-RENDITION-ID="9ed92c59cfe50cef30065b91abd1f5fe72a1aa29523d9e7603cd02941b3eb259",URI="https://vod-ap-amt.tv.apple.com/itunes-assets/HLSVideo114/v4/34/f2/d1/34f2d171-b10c-382f-d6cd-f713735a7651/P186755466_A1490366967_FF_en_subtitles.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_ak",LANGUAGE="en",NAME="English ",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound",FORCED=NO,STABLE-RENDITION-ID="9ed92c59cfe50cef30065b91abd1f5fe72a1aa29523d9e7603cd02941b3eb259",URI="https://vod-ak-amt.tv.apple.com/itunes-assets/HLSVideo114/v4/34/f2/d1/34f2d171-b10c-382f-d6cd-f713735a7651/P186755466_A1490366967_FF_en_subtitles.m3u8"

**Comment by MichaelYochpaz** [comment]
Has been fixed in v1.0.3
