### ISSUE TITLE
[Feature Request]: Add year to ZIP files

### ISSUE THREAD

**Issue by insurw** [MichaelYochpaz/iSubRip#31]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing issue with a request for the feature I want to requst.

### Description

If ripped individually the subtitles will always have a year in the title. Same for the subtitles in the ZIPs.

I think the ZIP files will only have year if the iTunes URL contains it. iTunes isn't consistent in having a year in URL for movies to avoid name collisions.

Example:
https://itunes.apple.com/se/movie/pinocchio/id540283464?l=en
https://itunes.apple.com/se/movie/pinocchio/id1597469980?l=en

**Comment by MichaelYochpaz** [comment]
Thanks for reporting.
Fixed in the latest release (v2.3.3).

**Comment by insurw** [comment]
Thanks! Though I found a small issue when the movie title contains the year. You'll get double years, but it's not really that important. It's more important having the year in the ZIP file name. 
iTunes kinda sucks regarding the year data. The year on the movie page seems to be the region's release date. So you get silly things like "Fantasia (1940)" having a release date of 1990. So in a way it's good to have double years.

Cinderella.1950.1950.iT.WEB
https://itunes.apple.com/se/movie/cinderella-1950/id1339827782?l=en

Dumbo.1941.1946.iT.WEB
https://itunes.apple.com/se/movie/dumbo-1941/id1338970937?l=en

Fantasia.1940.1990.iT.WEB
https://itunes.apple.com/se/movie/fantasia-1940/id1429270511?l=en

**Comment by insurw** [comment]
> Thanks for the suggestion. Added in the latest release (v2.3.3).

Thanks! Though I found a small issue when the movie title contains the year. You'll get double years, but it's not really that important. It's more important having the year in the ZIP file name. 
iTunes kinda sucks regarding the year data. The year on the movie page seems to be the region's release date. So you get silly things like "Fantasia (1940)" having a release date of 1990. So in a way it's good to have double years.

Cinderella.1950.1950.iT.WEB
https://itunes.apple.com/se/movie/cinderella-1950/id1339827782?l=en

Dumbo.1941.1946.iT.WEB
https://itunes.apple.com/se/movie/dumbo-1941/id1338970937?l=en

Fantasia.1940.1990.iT.WEB
https://itunes.apple.com/se/movie/fantasia-1940/id1429270511?l=en

**Comment by insurw** [comment]
I checked a few movies. If you scraped copyright instead of released year you'd get the correct year.

**Comment by MichaelYochpaz** [comment]
Thanks for reporting.
I've pushed a fix (6a0bc2de4ad301f90faa359dc72f5b2d4407fae4) for cases where thesame  year is already in the title (like `Cinderella.1950.1950.iT.WEB`).
I actually had this in mind while working on the fix for this issue, but I forgot to implement it.

As for cases where the year in title and the release year on the metadata mismatch, it will remain as it currently is (like `Dumbo.1941.1946.iT.WEB` for example) for now, as I don't have a simple solution in mind at the moment.

The original release year like (1941 in Dumbo's case) should be the correct one, but taking the release year from the title is problematic as it could be part of the title (for example: "2012" and "1917" are both movie names).

Using the copyright is not reliable enough.

I'll keep that in mind though and see if I can find a solution.

**Comment by insurw** [comment]
> Using the copyright is not reliable enough.

How so? That it's available or accuracy?
I checked copyright year for a few iTunes movies on US store and they seem to be correct. One was off by one year.

I've done 1.4k rips on the Swedish store. I'd say about 1/3-1/4 have incorrect year using released. A lot of them are off by 1-2 year (because of Swedish region released date) but a lot also have decades in difference.

**Comment by insurw** [comment]
@MichaelYochpaz I checked a few more movies (Swedish store) and **a lot** them have released year one year later than copyright year. "Copyright year" is what IMDB, TMDB, Wikipedia have. IMO released year is what's not reliable.

If you only look at the US store I guess you could say the few times it's incorrect makes it "unreliable".
In the Swedish store (and probably other languages) the year is wrong a lot.
