### ISSUE TITLE
[Feature Request]: downloading from multiple URLs at once

### ISSUE THREAD

**Issue by yoavoffek** [MichaelYochpaz/iSubRip#37]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing issue with a request for the feature I want to requst.

### Description

Can support be added so that instead of the syntax "isubrip [itunes/appleTV link]", we could input a path to a txt or even xml file that contains multiple iTunes movie links, so that isubrip will rip the subtitles from all links with one command rather than a separate command for each link?

**Comment by MichaelYochpaz** [comment]
You can already pass multiple URLs using the command line.
For example: ```isubrip <link1> <link2> <link3>...```

**Comment by yoavoffek** [comment]
I see, will try. Thanks!
