### ISSUE TITLE
[Question]: Why not update double year fix?

### ISSUE THREAD

**Issue by insurw** [MichaelYochpaz/iSubRip#38]
### Question

I tested it and it works fine. Is it not enough big change to warrant an update?

Also could you please answer my questions about scraping copyright year? Thanks.
https://github.com/MichaelYochpaz/iSubRip/issues/31#issuecomment-1276864088
https://github.com/MichaelYochpaz/iSubRip/issues/31#issuecomment-1286825468

**Comment by MichaelYochpaz** [comment]
You should be able to comment on an issue even if it's closed,  
so please don't open new issues asking to answer a question on another issue.

---

> Is it not enough big change to warrant an update?

No.  
You can install the package from git to get the latest commits on GitHub. Instructions can be found [here](https://github.com/MichaelYochpaz/iSubRip#git-source-code).

> Also could you please answer my questions about scraping copyright year? Thanks.

This issue requires research, and I've been very busy lately.  
Having the correct year in the filename is a low-priority issue. You can always just rename the files.
