### ISSUE TITLE
[Issue]: tv.apple.com aren't recognized

### ISSUE THREAD

**Issue by mastercho** [MichaelYochpaz/iSubRip#40]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.10.0

### Package Version

2.3.3

### Description

Package seems to be outdated because its not recognizing urls anymore i tried following

https://tv.apple.com/us/show/blade-the-series/umc.cmc.20yikft1ykcpl0yohd1tmep9q?at=1000l3V2

https://itunes.apple.com/us/tv-season/blade-the-series-season-1/id161811818

### Output Log

```Text
C:\Users\Ninja\Desktop>isubrip https://itunes.apple.com/us/tv-season/blade-the-series-season-1/id161811818
Scraping https://itunes.apple.com/us/tv-season/blade-the-series-season-1/id161811818...
Error: https://itunes.apple.com/us/tv-season/blade-the-series-season-1/id161811818 is not a valid iTunes/AppleTV movie URL.

C:\Users\Ninja\Desktop>isubrip https://tv.apple.com/us/show/blade-the-series/umc.cmc.20yikft1ykcpl0yohd1tmep9q?at=1000l3V2
Scraping https://tv.apple.com/us/show/blade-the-series/umc.cmc.20yikft1ykcpl0yohd1tmep9q?at=1000l3V2...
Error: https://tv.apple.com/us/show/blade-the-series/umc.cmc.20yikft1ykcpl0yohd1tmep9q?at=1000l3V2 is not a valid iTunes/AppleTV movie URL.
```

**Comment by MichaelYochpaz** [comment]
Hey @mastercho, subtitles scraping for series is not supported by iSubRip.  
If you'll enter a URL of an iTunes movie, it will work fine.
