### ISSUE TITLE
[Issue]: Cannot download english version of subtitles

### ISSUE THREAD

**Issue by jbehrmusic** [MichaelYochpaz/iSubRip#47]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.11.4

### Package Version

2.4.3

### Description

This Apple movie states it has English subtitles within the Subtitles section at the bottom, but they are not downloading via isubrip

### Output Log

```Text
isubrip https://tv.apple.com/us/movie/tracing-skylines/umc.cmc.4fbxsitwvsslpatrh2x89t9rt
Scraping https://tv.apple.com/us/movie/tracing-skylines/umc.cmc.4fbxsitwvsslpatrh2x89t9rt
Found movie: Tracing Skylines (2013)
Deutsch (Deutschland) (de-DE) subtitles were successfully downloaded.
Español (es) subtitles were successfully downloaded.
Français (France) (fr-FR) subtitles were successfully downloaded.
Italiano (it) subtitles were successfully downloaded.
Nederlands (nl) subtitles were successfully downloaded.

5/5 matching subtitles have been successfully downloaded.
```

**Comment by MichaelYochpaz** [comment]
See https://github.com/MichaelYochpaz/iSubRip/issues/16 and https://github.com/MichaelYochpaz/iSubRip/issues/18
