### ISSUE TITLE
Converting the script to an executable

### ISSUE THREAD

**Issue by Essam311** [MichaelYochpaz/iSubRip#5]
Hi, could you convert the script to an executable so the novice users would be able to use it without the need for knowing how to use python? Something like this one

[iSubRip_v1.0.3_with_ffmpeg.zip](https://github.com/MichaelYochpaz/iSubRip/files/6447589/iSubRip_v1.0.3_with_ffmpeg.zip)

I made it to myself using auto-py-to-exe, I added a batch file Download.bat to make the downloading process easier by just opening the batch file with notepad and adding the movie's link and saving the file then running the batch file.

I added ffmpeg.exe in the same folder with iSubRip.exe so no need for adding ffmpeg.exe to the PATH.

**Comment by MichaelYochpaz** [comment]
No, there won't be any exe releases for this script as this adds unnecessary time-consuming complexity.
Feel free to compile it yourself for personal use if you feel like it though.
