### ISSUE TITLE
[Issue]: Redirect URL not found?

### ISSUE THREAD

**Issue by lolipopsz** [MichaelYochpaz/iSubRip#52]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.11.5

### Package Version

2.4.3

### Description

this url `https://itunes.apple.com/sg/movie/top-gun-maverick/id1622175422` produces error this error. but this one works fine `https://tv.apple.com/sg/movie/top-gun-maverick/umc.cmc.670544bajp6s4pysx4rvctczz`

### Output Log

```Text
isubrip https://itunes.apple.com/sg/movie/top-gun-maverick/id1622175422
Scraping https://itunes.apple.com/sg/movie/top-gun-maverick/id1622175422
Error: Apple TV redirect URL not found.
```

**Comment by MichaelYochpaz** [comment]
Hey @lolipopsz, this issue doesn't seem to reproduce for me (subtitles are downloaded successfully using the iTunes link you provided).
Could you retry and see if you still experience this issue?
It might be some connectivity issue on your side / Apple's side when you ran it.

**Comment by PatrBal** [comment]
Same issue here.

**Comment by MichaelYochpaz** [comment]
> Same issue here.

@PatrBal For what URL?

**Comment by PatrBal** [comment]
@MichaelYochpaz
```
$ isubrip https://itunes.apple.com/us/movie/the-machine/id1689512351
Scraping https://itunes.apple.com/us/movie/the-machine/id1689512351
Error: Apple TV redirect URL not found.
```
but
```
$ isubrip https://tv.apple.com/us/movie/the-machine/umc.cmc.2zfbbxfj7fnnsqp0tqdriurga
Scraping https://tv.apple.com/us/movie/the-machine/umc.cmc.2zfbbxfj7fnnsqp0tqdriurga
Found movie: The Machine (2023)
```
works and all the subtitles are downloaded.

**Comment by MichaelYochpaz** [comment]
@PatrBal Interesting... It doesn't reproduce for me either. Using this iTunes URL works fine for me as well.
Does entering https://itunes.apple.com/us/movie/the-machine/id1689512351 from the browser successfully redirects you to the AppleTV URL?

**Comment by PatrBal** [comment]
@MichaelYochpaz
Does entering https://itunes.apple.com/us/movie/the-machine/id1689512351 from the browser successfully redirects you to the AppleTV URL?
Yes, it does.

**Comment by PatrBal** [comment]
I am on macOS. It could be the origin of the problem. Indeed, clicking on a link to  https://itunes.apple.com/us/movie/the-machine/id1689512351 in the browser, actually open the "TV"app.

**Comment by MichaelYochpaz** [comment]
@lolipopsz @PatrBal I've added logs on the new release ([v2.5.0](https://github.com/MichaelYochpaz/iSubRip/releases/tag/v2.5.0)) that should help debug such issues.
If the issue persists, could you please send me a log file of such case so that I can further investigate this issue?

You can find information about where to find logs [here](https://github.com/MichaelYochpaz/iSubRip#logs).

**Comment by MichaelYochpaz** [comment]
Closing due to no response.
Feel free to comment here (preferably with logs) if the issue reproduces, and I'll re-open it.
