### ISSUE TITLE
[Feature Request]: Output formatting to improve information understanding.

### ISSUE THREAD

**Issue by rDamascena** [MichaelYochpaz/iSubRip#54]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing issue with my feature request.

### Description

`Some suggestions for improve information understanding.`

$ isubrip "https://tv.apple.com/br/movie/que-horas-eu-te-pego/umc.cmc.jv4x80nydofuh6a5b1nmg5kc"
User config file detected at 'C:\Users\Adriana\\.isubrip\config.toml' and will be used.
Scraping 'https://tv.apple.com/br/movie/que-horas-eu-te-pego/umc.cmc.jv4x80nydofuh6a5b1nmg5kc'...
*
Found movie: No Hard Feelings [2023] (ID: 1690701761)
*
العربية (ar) subtitles were successfully downloaded.
български (bg) subtitles were successfully downloaded.
中文（简体） (cmn-Hans) subtitles were successfully downloaded.
中文（繁體） (cmn-Hant) subtitles were successfully downloaded.
Čeština (cs) subtitles were successfully downloaded.
dansk (da) subtitles were successfully downloaded.
Deutsch (Deutschland) (de-DE) subtitles were successfully downloaded.
Ελληνικά (el) subtitles were successfully downloaded.
English (UK) (en-GB) subtitles were successfully downloaded.
English (en) [Forced] subtitles were successfully downloaded.
Español (Latinoamérica) (es-419) subtitles were successfully downloaded.
Español (España) (es-ES) subtitles were successfully downloaded.
eesti (et) subtitles were successfully downloaded.
Suomi (fi) subtitles were successfully downloaded.
Français (France) (fr-FR) subtitles were successfully downloaded.
עברית (he) subtitles were successfully downloaded.
magyar (hu) subtitles were successfully downloaded.
Italiano (Italia) (it-IT) subtitles were successfully downloaded.
한국어 (ko) subtitles were successfully downloaded.
lietuvių (lt) subtitles were successfully downloaded.
latviešu (lv) subtitles were successfully downloaded.
Nederlands (nl) subtitles were successfully downloaded.
norsk (no) subtitles were successfully downloaded.
polski (pl) subtitles were successfully downloaded.
Português (Brasil) (pt-BR) subtitles were successfully downloaded.
Português (Brasil) (pt-BR) [Forced] subtitles were successfully downloaded.
português (Portugal) (pt-PT) subtitles were successfully downloaded.
Русский (ru) subtitles were successfully downloaded.
Slovenčina (sk) subtitles were successfully downloaded.
slovenščina (sl) subtitles were successfully downloaded.
Svenska (sv) subtitles were successfully downloaded.
ไทย (th) subtitles were successfully downloaded.
Türkçe (tr) subtitles were successfully downloaded.
українська (uk) subtitles were successfully downloaded.
廣東話 (yue-Hant) subtitles were successfully downloaded.
English (US) (en-US) [CC] subtitles were successfully downloaded.
*
**36/36 matching subtitles have been successfully downloaded.

```
Suggestions:

*Add two line breaks.
**36/36 matching subtitles for "No Hard Feelings" has been downloaded from 1 playlist to "folder_path".
```

**Comment by MichaelYochpaz** [comment]
Hey, thanks for the suggestion.
The current output is just log output, and in my logging empty log lines to make the CLI output prettier is not a good logging practice.
I might implement a better output system which is separated from the logging system at some point in the future, but currently, as long as the CLI output just represents the logs, the priority is to log everything in a readable and compact manner and not to make it look pretty.
