### ISSUE TITLE
[Feature Request]: information on release dates from all countries

### ISSUE THREAD

**Issue by NaorSevilia** [MichaelYochpaz/iSubRip#59]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing issue with my feature request.

### Description

Is it possible to get information on release dates from all countries? like (us/ca/se/il/hn/mx) all country...

in CMD - isubrip LINK

---Example---

Scraping https://tv.apple.com/movie/wonka/umc.cmc.4t8k4gg3h0sy8ob4xr3twj3lc
Found movie: Wonka (2023)

Pre-Orders(US): עברית Release Date: 2024-02-09.
Pre-Orders(CA): עברית Release Date: 2024-05-12.
Pre-Orders(MX): עברית Release Date: 2024-07-24.
Pre-Orders(IL): עברית Release Date: 2024-09-01.
Pre-Orders(NZ): עברית Release Date: 2024-04-17.

Thank YOU.
(I have the shorthand names if you need)

**Comment by MichaelYochpaz** [comment]
Hey @NaorSevilia, thank you for the suggestion.
I already thought of it before, and found that this is much more work than it seems.
There isn't (as far as I know) a single API endpoint that provides information on all stores, and I don't like the idea of querying each storefront ("country") individually (there are 180+ different stores).

Different stores can also point to different iTunes playlists (which could mean different subtitles, and different subtitles timings), which adds additional complexity.

Closing as this is not planned for now.
