### ISSUE TITLE
The script stopped working

### ISSUE THREAD

**Issue by Essam311** [MichaelYochpaz/iSubRip#6]
Hi, the script stopped working because iTunes changed the GROUP-ID in the playlist .

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_vod-ap3-amt.tv.apple.com",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="55653e6317a4e49b7bb9b7124feea77224bee9c044764a3f07c49f052face22b",URI="https://vod-ap3-amt.tv.apple.com/itunes-assets/HLSVideo124/v4/2d/07/c9/2d07c9c5-cd6b-0bdd-0071-3ef7955c3d86/P236366768_A965491522_FF_ar_subtitles.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_vod-ak-amt.tv.apple.com",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="55653e6317a4e49b7bb9b7124feea77224bee9c044764a3f07c49f052face22b",URI="https://vod-ak-amt.tv.apple.com/itunes-assets/HLSVideo124/v4/2d/07/c9/2d07c9c5-cd6b-0bdd-0071-3ef7955c3d86/P236366768_A965491522_FF_ar_subtitles.m3u8"

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_vod-ap-amt.tv.apple.com",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="428b51a5addbf1d8409cc348b0e2deb5dd15d38e46fc13ae94185a5cd2d40733",URI="https://vod-ap-amt.tv.apple.com/itunes-assets/HLSVideo114/v4/f1/b0/6d/f1b06ddc-7964-e432-57b2-59ed727dc770/P185792533_A270199674_FF_ar_subtitles_B8379289.m3u8"

The fixed script.

https://codeload.github.com/Essam311/iSubRip/zip/refs/heads/main

https://github.com/Essam311/iSubRip/commit/55bedff10240c2faac3996e58b05daeb493f8280

**Comment by D-LUFFY89** [comment]
Some experience showing an error message

https://i.imgur.com/wO0lD2k.jpg
Hello Essam311, I was trying to message you, but I do not have Facebook, Twitter, or any social media of your own 

Do you have any idea to download subtitles from philo.com 
Free registration without subscription
