### ISSUE TITLE
[Feature Request]: הורדת "תרגום" אחרי סריקה של כל המדינות

### ISSUE THREAD

**Issue by NaorSevilia** [MichaelYochpaz/iSubRip#60]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing issue with my feature request.

### Description

הורדה של כתוביות למשל "עברית" לפי קישור הסרט אייטונס וזה מריץ סריקה על כל המדינות.
וככה זה בעצם מוריד את "העברית" אחרי סריקה של המדינות

לפעמים יש תרגומים שזמינים במדינות שונות שלא זמינות בישראל אבל התרגום זמין במדינות שונות
אם יהיה דבר כזה זה יחסוך ים של עבודת חיפוש.

הודה לך מאווד אם זה אפשרי
וכמובן אם הסרט עוד לא שוחרר שיהיה רשימה של תאריכי שחרור של כל המדינות(הצעה הקודמת)
וככה בתאריך השחרור יהיה הרבה יותר קל לגשת לסרט ולמשוך את התרגום.

---דוגמא----

Scraping https://tv.apple.com/movie/wonka/umc.cmc.4t8k4gg3h0sy8ob4xr3twj3lc
Found movie: Wonka (2023)

Found  Subtitles(NZ): עברית
Found  Subtitles(US): עברית
Found  Subtitles:(CA) עברית
Found  Subtitles(IL): עברית
Found  Subtitles(DK): עברית

________________________________
במידה והסרט לא שוחרר או שחלק שוחררו

Scraping https://tv.apple.com/movie/wonka/umc.cmc.4t8k4gg3h0sy8ob4xr3twj3lc
Found movie: Wonka (2023)

Found  Subtitles(US): עברית
Pre-Orders(CA): עברית Release Date: 2024-02-09.
Pre-Orders(NZ): עברית Release Date: 2024-04-17.
Found  Subtitles(DK): עברית
Pre-Orders(IL): עברית Release Date: 2024-07-24.

תודה רבה..

**Comment by MichaelYochpaz** [comment]
Hey @NaorSevilia, same answer as I wrote you on https://github.com/MichaelYochpaz/iSubRip/issues/59 (you could've just opened these two as a single suggestion, since they're practically the same).
Also, please write your issues in English next time, as the issue / suggestion might be relevant for other users as well.
