### ISSUE TITLE
[Question]: Do you have any idea how to track all countries?

### ISSUE THREAD

**Issue by NaorSevilia** [MichaelYochpaz/iSubRip#61]
### Question

Do you have any idea how to track all countries?

**Comment by MichaelYochpaz** [comment]
Hey @NaorSevilia, please stop opening new issues on the same matter (https://github.com/MichaelYochpaz/iSubRip/issues/59, https://github.com/MichaelYochpaz/iSubRip/issues/60, and not this).
You can comment on an existing issue, even if it's closed.

As for the answer, the ones currently supported by iSubRip (which should be all, but I can't guarantee that) can be found here:
https://github.com/MichaelYochpaz/iSubRip/blob/main/isubrip/scrapers/appletv_scraper.py#L38-L64
Other than that, no. Not a simple one at least.

**Comment by NaorSevilia** [comment]
You should try to find a solution for a comprehensive search

isubrip https://itunes.apple.com/us/movie/sick/id1683398776 https://itunes.apple.com/ca/movie/sick/id1683398776 https://itunes.apple.com/il/movie/sick/id1683398776 https://itunes.apple.com/am/movie/sick/id1683398776 https://itunes.apple.com/az/movie/sick/id1683398776 https://itunes.apple.com/bh/movie/sick/id1683398776 https://itunes.apple.com/bw/movie/sick/id1683398776 https://itunes.apple.com/cv/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776

**Comment by NaorSevilia** [comment]
You should try to find a solution for a comprehensive search @MichaelYochpaz 

isubrip https://itunes.apple.com/us/movie/sick/id1683398776 https://itunes.apple.com/ca/movie/sick/id1683398776 https://itunes.apple.com/il/movie/sick/id1683398776 https://itunes.apple.com/am/movie/sick/id1683398776 https://itunes.apple.com/az/movie/sick/id1683398776 https://itunes.apple.com/bh/movie/sick/id1683398776 https://itunes.apple.com/bw/movie/sick/id1683398776 https://itunes.apple.com/cv/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776 https://itunes.apple.com/bg/movie/sick/id1683398776

**Comment by MichaelYochpaz** [comment]
@NaorSevilia [I already explained why this isn't possible (at least not in a reasonable way)](https://github.com/MichaelYochpaz/iSubRip/issues/59#issuecomment-1913280501).  
If you'll keep tagging me / open new issues on the exact same matter, I'll have to block you.

Feel free to develop such a solution yourself, I don't work for you.
