### ISSUE TITLE
[Issue]: Failed to download subtitles

### ISSUE THREAD

**Issue by boulderdash09** [MichaelYochpaz/iSubRip#71]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.12.2

### Package Version

2.5.4

### Description

Hi,

I'm facing an issue since version 2.5.3 (the same for 2.5.4) and I can't download my subtitles anymore. It just says "Failed to download xxxx", where xxxx is the sub's language. It seems to be a connection (timeout) issue so I tried a lot of things (DNS change, VPN, etc), but it didn't help... Maybe my connection is too slow but I don't know. 

If I rollback iSubRip to version 2.5.2 on my computer, it works again !

I know this issue is weird because 2.5.4 or 2.5.3 works fine for everyone, but not for me :)

Can you help me ?

### Output Log

```Text
[2024-05-17 16:24:29 | DEBUG | MainThread | __main__.py::download_subtitles::380] Debug information:
Traceback (most recent call last):
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_async\connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "......................AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "......................AppData\Local\Programs\Python\Python312\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:
```

### Config

```TOML
[downloads]
folder = "C:\\subrip"
languages = ["en-US", "fr-FR"]
overwrite-existing = true
zip = false

[subtitles]
convert-to-srt = true
fix-rtl = true

[subtitles.webvtt]
subrip-alignment-conversion = true
```

**Comment by MichaelYochpaz** [comment]
Hey @boulderdash09, these type of issues (networking & timeouts) are usually difficult to debug and are related to something with user's configuration, but I'll try my best to help.

Looking at the [diffs between v2.4.2 and v2.4.3](https://github.com/MichaelYochpaz/iSubRip/compare/v2.5.2...v2.5.3), I see two changes that might be related:
- Replace aiohttp with httpx (https://github.com/MichaelYochpaz/iSubRip/commit/bb0f6c76c3e20ca3243e74e22c628954a9c44d4f)
- Add proxy support  (https://github.com/MichaelYochpaz/iSubRip/commit/da5795affc867ebe2a1f16492898195b90bffcf3)

Could you check if you have any of the [environment variables `httpx` supports](https://www.python-httpx.org/environment_variables/) is set to a value, and if so, what the value is?

You can list your current environment variables by running `ls env:` on a PowerShell terminal.
I specifically suspect one of `HTTP_PROXY`, `HTTPS_PROXY`, and `ALL_PROXY` might be set to a proxy server that isn't active / working.

Did you perhaps download subtitles for a big amount of movies over a short period, causing a temporary block by the server?

Other than these checks - please attach the full log and not just the error message, as there's a lot of relevant information being logged that can help debug this issue.
Note that you can attach the log file in a new comment by dragging & dropping it into the comment box (should be more convenient). If you just paste in a comment / edit the original post, please make sure to use the following format:
````
```Text
<LOG GOES HERE>
```
````

**Comment by boulderdash09** [comment]
Hi @MichaelYochpaz and thank you for your feedback !

With your explanations, I think I found the problem but I changed the code to fix it.

In the class AsyncScraper (in scraper.py) I changed this :

        self._async_session = httpx.AsyncClient(
            headers={"User-Agent": self._user_agent},
            proxy=(httpx.Proxy(url=self._proxy) if self._proxy else None),
            verify=self._verify_ssl
        )

by this :

        self._async_session = httpx.AsyncClient(
            headers={"User-Agent": self._user_agent},
            proxy=(httpx.Proxy(url=self._proxy) if self._proxy else None),
            verify=self._verify_ssl,
            timeout=10.0
        )

And it works !

So I just added "timeout=10.0", as I read it's 5 by default. I think 5 is a bit short for my computer and/or configuration, I don't really know why however.

**Comment by MichaelYochpaz** [comment]
@boulderdash09 Nice find, thanks for reporting.
[Looks like `aiohttp` had 300 seconds (5 minutes) timeout by default](https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts), which explains the difference.

5 seconds is plenty of time for the simple requests `isubrip` makes (and seems like it works for most users), as I don't believe it ever fetches more than a few KB in a single request (subtitles on iTunes are split into many very small chunks of something like 10-30 text lines. For most users, even 2 seconds is probably more than enough).

So regardless to `isubrip`, I'd suggest checking if you have a firewall, a very slow VPN / proxy in-use, or any other network-related software that might cause big delays. Could also just be your ISP being terrible (in which case there isn't really much you can do besides switching).

I'll have to check and consider increasing the default timeout value, as if there is a network issue, the program will wait for the full timeout to pass before failing, so it might seem unresponsive (For example, if you have no internet connection, and there's a 30 seconds timeout, the program will wait 30 seconds for a response with nothing happening, and only then fail with an error), so I can't guarantee I'll update that, I'll have to think about it.

But in any case, adding a config setting to update the timeout seems like a good idea to me, and will allow you to just add something like:
```toml
[scrapers]
timeout = 10
```
to your config to resolve this issue.

Keeping this issue open until a solution is implemented.

**Comment by boulderdash09** [comment]
Thank you @MichaelYochpaz 

I think my VPN is the root problem here after some more tests. However, having a config for the timeout is an excellent idea, it's easy (because the config file doesn't change when a new version is installed) and can solve the issue in just on line. Also useful if someone else has a similar problem.

**Comment by MichaelYochpaz** [comment]
Closing as `timeout` configuration options have been added on the latest 2.5.5 version :)
(Check the release-notes / [example config](https://github.com/MichaelYochpaz/iSubRip/blob/main/config.toml) for more information).
