### ISSUE TITLE
[Issue]: It doesn't update

### ISSUE THREAD

**Issue by TJruee** [MichaelYochpaz/iSubRip#73]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.12

### Package Version

2.5.5

### Description

This message is still displayed after an update

You are currently using version '2.5.4' of 'isubrip', however version '2.5.5' is available.
Consider upgrading by running "python3 -m pip install --upgrade isubrip"

### Output Log

```Text
C:\Users\Truee>isubrip https://tv.apple.com/us/movie/umc.cmc.40g49ntcfmu55zcsyqez79dni
User config file detected at 'C:\Users\Truee\.isubrip\config.toml' and will be used.
You are currently using version '2.5.4' of 'isubrip', however version '2.5.5' is available.
Consider upgrading by running "python3 -m pip install --upgrade isubrip"

Scraping 'https://tv.apple.com/us/movie/umc.cmc.40g49ntcfmu55zcsyqez79dni'...
Found movie: Horizon: An American Saga Chapter 1 [2024] (ID: 1752266257)
'Horizon: An American Saga Chapter 1' is currently unavailable on iTunes, and will be available on 2024-07-16.
```

**Comment by MichaelYochpaz** [comment]
Hey, thank you for reporting!

Seems like there was a build issue for the new version and for some the version hasn't been changed in the metadata, so while the package did update, it just reported that it's still on version 2.5.4, causing the update message to appear.

I've pushed a new release (v2.5.6) that should resolve this.
