### ISSUE TITLE
English Closed Caption subtitles 

### ISSUE THREAD

**Issue by gbronca** [MichaelYochpaz/iSubRip#75]
### Question

How can we download CC subtitles with iSubRip? I'm using Python 3.12.4 and iSubRip 2.5.6, and I can see that CC subtitles are listed as an option, but iSubRip never downloads them. I can't see a setting to enable it.

**Comment by MichaelYochpaz** [comment]
Hey @gbronca,
CC subtitles are embedded within the video stream, so iSubRip can't download those. See https://github.com/MichaelYochpaz/iSubRip/issues/16

**Comment by gbronca** [comment]
Thanks, @MichaelYochpaz. I didn't know that, but it makes sense.
