### ISSUE TITLE
this happaned again No subtitles matching the filter were found. Download failed.

### ISSUE THREAD

**Issue by D00oo00M** [MichaelYochpaz/iSubRip#8]
yesterday its work in 1.0.4 fix and today its happaned again
the error
https://i.imgur.com/S2LrIm2.png

**Comment by Essam3111** [comment]
@MichaelYochpaz iTunes still using the GROUP-ID "subtitles_ak", I modified the script by replacing 

`p.group_id == "subtitles_vod-ak-amt.tv.apple.com"`

with

`(p.group_id == "subtitles_ak" or p.group_id == "subtitles_vod-ak-amt.tv.apple.com")`

and I was able to download the subtitles from the link

https://itunes.apple.com/il/movie/batman-1966/id280315278

[Batman.1966.iT.WEB.zip](https://github.com/MichaelYochpaz/iSubRip/files/6549612/Batman.1966.iT.WEB.zip)



https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/playlist.m3u8?cc=IL&a=280315278&id=185492124&l=en&aec=SD

#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.accessibility",VALUE="CC,SDH"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.feature.adam-id",VALUE="280315278"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.title",VALUE="Batman (1966)",LANGUAGE="en-us"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.poster",VALUE="https://is4-ssl.mzstatic.com/image/thumb/SLnqDGi1_EGWIvh_VVx4Jg/{w}x{h}bb.{f}",LANGUAGE="en-us"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.genre",VALUE="Action & Adventure",LANGUAGE="en-us"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.release-date",VALUE="1966-07-30T07:00:00Z"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.rating-tag",VALUE="UR"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.rating-system",VALUE="il-movies"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.rating-rank",VALUE="900"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.rt-audience-score",VALUE="0.79"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.rt-rating",VALUE="FRESH"
#EXT-X-SESSION-DATA:DATA-ID="com.apple.hls.description",VALUE="Batman (Adam West) and Robin (Burt Ward) must launch a rescue mission when they get a tip that Commodore Schmidlapp (Reginald Denny) is in danger aboard his yacht.  But the tip is a set-up by four of the most powerful villains ever, who seek to defeat the dynamic duo once and for all! Armed with a dehydrator that can turn humans into dust, the fearsome foursome intends to take over the world!  Can the Caped Crusaders use their high-flying heroism and groovy gadgetry to declaw Catwoman (Lee Meriwether), ice the Penguin (Burgess Meredith), upstage the Joker (Cesar Romero), and stump the Riddler (Frank Gorshin) in time?",LANGUAGE="en-us"

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_ap",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="a65b8d159982025450433bb60faa5af8db407c6560748e4eea470108b76295ba",URI="https://vod-ap-amt.tv.apple.com/itunes-assets/HLSVideo124/v4/ff/1e/cf/ff1ecfaa-a397-29b1-0587-6654a83b4516/P185492124_A280315278_FF_ar_subtitles.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_ak",LANGUAGE="ar",NAME="العربية",AUTOSELECT=YES,FORCED=NO,STABLE-RENDITION-ID="a65b8d159982025450433bb60faa5af8db407c6560748e4eea470108b76295ba",URI="https://vod-ak-amt.tv.apple.com/itunes-assets/HLSVideo124/v4/ff/1e/cf/ff1ecfaa-a397-29b1-0587-6654a83b4516/P185492124_A280315278_FF_ar_subtitles.m3u8"

**Comment by MichaelYochpaz** [comment]
@Essam3111 that indeed seems to be the issue.
Fixed in v1.0.5
